In [1]:
import numpy as np
import scipy
import scipy.linalg
import warnings

In [2]:
warnings.filterwarnings('ignore')

**2. Найдите псевдорешение:**  
x + 2y – z = 1  
3x – 4y = 7  
8x – 5y + 2z = 12  
2x – 5z = 7  
11x +4y – 7z = 15

In [3]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
x, y, z = np.linalg.lstsq(A, B)[0]
print('x =', x, 'y =', y, 'z =', z)

x = 1.1391935264660065 y = -0.9049844399605508 z = -0.9009802999097406


**3. Сколько решений имеет линейная система:**    
(1 2 3)     (12)  
(4 5 6)  X  (2 )   
(7 8 9)     (1 )   
Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

вычислим определитель матрицы А

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])

In [5]:
np.linalg.det(A)

6.66133814775094e-16

вычислим ранг основной и расширенной матрицы:

In [6]:
C = np.concatenate((A,B.T), axis=1)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

(2, 3)

у нас и определитель равен 0 и ранг основной матрицы меньше ранга расширенной матрицы, что, по теореме Кронекера-Капелли, означает несовместную систему. а значит точного решения нет

изменим правую часть, чтобы сделать систему совместной и найдем решение:

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 15, 18])
x, y, z = np.linalg.solve(A, B)
print('x =', x, 'y =', y, 'z =', z)

x = -18.0 y = 27.0 z = -8.0


**4. Вычислите LU-разложение матрицы:**  
1  2  3  
2 16 21  
4 28 73  
После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [8]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)
print('P =', P)
print('L =', L)
print('U =', U)

P = [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L = [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U = [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [9]:
B = np.array([12, 2, 1])

In [10]:
x, y, z = np.linalg.solve(A, B)
print('x =', x, 'y =', y, 'z =', z)

x = 15.810185185185185 y = -1.474537037037037 z = -0.28703703703703703


**5. Найдите нормальное псевдорешение недоопределенной системы:**  
x + 2y – z = 1  
8x – 5y + 2z = 12  
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 

In [11]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])
x, y, z = np.linalg.lstsq(A, B)[0]
print('x =', x, 'y =', y, 'z =', z)

x = 1.3819188191881924 y = -0.18081180811808029 z = 0.020295202952029134


**6. Найдите одно из псевдорешений вырожденной системы:**  
(1 2 3) (2)  
(4 5 6) X (5)  
(7 8 9) (11)  
Попробуйте также отыскать и нормальное псевдорешение.

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)
print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.77635684e-15]]


In [13]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [14]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  8.43769499e-15])

In [15]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 9.32822279e-15])

In [16]:
X = np.append(X1, 0)
print(X)

[1.50000000e+00 9.32822279e-15 0.00000000e+00]
